version: '3'

services:
  db:
    privileged: true
    image: mysql:8.0.30
    container_name: antenna-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Antenna@58.com
      MYSQL_DATABASE: antenna
    networks:
      - antenna
    restart: always


  antenna:
    build: ./
    image: antenna:latest
    depends_on:
      - db
    container_name: antenna
    volumes:
      - ./:/antenna
      - type: bind
        source: ./conf/antenna.ini
        target: /etc/supervisor.d/antenna.ini
    ports:
      - "21:21"
      - "80:80"
      - "2345:2345"
      - "53:53/udp"
      - "443:443"
    environment:
      # 平台数据库配置，与上mysql配置保持一致
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: Antenna@58.com
    env_file:
      - .env
    networks:
      - antenna
    restart: always

networks:
  antenna:
    driver: bridge
